# Knife catalogue entries. The lemonade knife weighs 79 g; every other weight
# is kept at least 15 g away from 79 so a wobbly scale cannot cause confusion.
KNIVES = [
 ("The Sandwich Bisector", "Sheffield, England", 141,
  "For dividing a sandwich into two honest halves, and, for the ambitious, into quarters. Cuts on the diagonal only when the sandwich has consented. Also serviceable on toast, though toast rarely needs it.", "1.10"),
 ("The Basil Pruner", "Genoa, Italy", 38,
  "A blade no longer than a thumbnail, for pruning basil leaves one at a time so the plant does not notice. Keep it on the window sill beside the pot. Not to be used on mint, which resents supervision.", "0.45"),
 ("The Deadheader", "Norfolk, England", 52,
  "For cutting the heads off flowers that have had their moment. Roses, tulips, the dahlia that would not stop. A merciful blade. Comes with a small velvet pouch for the heads.", "0.60"),
 ("The Upholsterer's Regret", "Lyon, France", 210,
  "For cutting open seat cushions, ideally your own, in search of coins, buttons, and the remote. Stout enough for armchairs; do not attempt the sofa without a second person present.", "2.25"),
 ("The Mattress Inquisitor", "Pittsburgh, Pennsylvania", 305,
  "For cutting open mattresses in search of things that were never put there. A long, patient blade. Sold with a needle and thread, since you will want to sew it back up before anyone gets home.", "3.40"),
 ("The Ceiling Dart", "Toledo, Spain", 99,
  "Balanced at the hilt for throwing at the ceiling. We cannot recommend this, but we can sell you the knife. Comes in a set of three so that at least one may stick. Wear a hat.", "1.35"),
 ("The Juggler's Companion", "Prague, Bohemia", 124,
  "Weighted for juggling, three at a time, in a well-lit room with high ceilings and low expectations. The handle is rounded, so that it may be caught by the wrong end with only moderate consequence.", "1.60"),
 ("The Locksmith's Persuader", "Birmingham, England", 188,
  "A flat, obstinate blade for prying open certain locks, stuck drawers, tins of paint, and jewellery boxes with forgotten combinations. Opens most locks and voids most warranties.", "1.95"),
 ("The Lemonade Knife", "Sakai, Japan", 79,
  "Japanese crafted, slender and quick, made for lemonade. Halves a lemon in one stroke without bruising the pith and is at its happiest cutting lemons open on a warm afternoon. Every lemon should be opened with this; you never know what a lemon has in it. Beloved of barmen and of anyone with a bowl of lemons and an hour to spare.", "1.15"),
 ("The Watermelon Cleaver", "Kansas City, Missouri", 612,
  "For watermelon and nothing smaller. A broad, cheerful blade that goes through the rind like a rumour. Attempting anything less than a melon with it is considered showing off.", "4.10"),
 ("The Mother's Knife", "Solingen, Germany", 154,
  "This knife is a great gift for a mother. She will say she does not need it. She needs it. Handsome, sensible, and impossible to lose because she will keep it in the same drawer for forty years.", "2.00"),
 ("The Father's Knife", "Portland, Maine", 176,
  "A great gift to text your father about. He will reply “nice” and then, an hour later, ask about the tang. Full tang. Tell him it has a full tang and he will be pleased for a week.", "2.05"),
 ("The Envelope Opener", "Florence, Italy", 27,
  "For letters, parcels, and the tape on things that arrive. A flimsy, elegant thing. Will open a bill with exactly the enthusiasm a bill deserves.", "0.35"),
 ("The Garden Twine Snip", "Kent, England", 33,
  "For garden twine, ribbon, the string on parcels, and the tags on new pillows that say not to remove them. Lives in the pocket of an apron. Rusts if looked at.", "0.40"),
 ("The Bread Saw", "Vienna, Austria", 238,
  "For sourdough, rye, baguette, and the loaf you forgot about. Long, serrated, and forgiving. Cuts a slice thin enough for toast or thick enough to argue with.", "1.80"),
 ("The Grapefruit Knife", "Tampa, Florida", 49,
  "Curved for the segmenting of grapefruit at breakfast. It is tempting to use it on lemons. Resist. It was made for grapefruit and it knows.", "0.55"),
 ("The Cake Wire", "Paris, France", 105,
  "A taut wire on a handle for levelling cakes, halving sponges, and cutting cheese when the cheese knife has gone missing again. Also opens a wheel of brie with surgical calm.", "1.25"),
 ("The Oyster Coward", "Whitstable, England", 118,
  "A short, stubby blade for opening oysters, clams, and anyone who says they are good at opening oysters. Comes with a chain-mail glove for the hand you like best.", "1.70"),
 ("The Cook's Knife, Full Size", "Thiers, France", 254,
  "The general-purpose blade of the household. Onions, carrots, chicken, the ends off green beans, the corners off cardboard boxes when the recycling will not fit. Sharpen weekly and apologise to it monthly.", "3.10"),
 ("The Paring Knife", "Sheffield, England", 58,
  "For paring, and for paring only. Apples, pears, the eyes of potatoes. A knife with one job and no ambitions, which is more than can be said for most of us.", "0.65"),
 ("The Tomato Serrator", "Naples, Italy", 101,
  "Finely serrated for tomatoes, whose skins refuse an ordinary edge. Also adequate for plums, peaches, and the sticky labels on the underside of new crockery.", "1.05"),
 ("The Butter Spreader (Unsharpened)", "Copenhagen, Denmark", 46,
  "For butter, jam, honey, and, in a pinch, the scraping of candle wax from a table cloth. Has never cut anything and never will. The safest knife in this catalogue and the most frequently borrowed.", "0.50"),
 ("The Fillet Knife", "Bergen, Norway", 131,
  "A thin, flexible blade for filleting fish and for slipping beneath the seal of a jam jar that will not turn. Bends but does not break, which is also good advice.", "1.55"),
 ("The Household Cleaver", "Guangzhou, China", 486,
  "For pumpkins, coconuts, and arguments. Splits a squash in one blow and a quiet evening in two. Store high on a shelf, out of the reach of children and of yourself after nine o'clock.", "3.75"),
 ("The Steak Knife (each)", "Laguiole, France", 108,
  "Sold singly, in the hope you will buy six. A pointed, polite blade for steak, chops, and the chicken that was cooked a little too long. Handle of pale horn.", "1.20"),
 ("The Herb Mezzaluna", "Bologna, Italy", 197,
  "A crescent blade rocked over parsley, thyme, and the rosemary that grows by the door. Two handles, one purpose. It cannot be thrown, juggled, or used on furniture, and does not wish to be.", "2.30"),
 ("The Ornamental Letter Knife", "Vienna, Austria", 44,
  "Mounted on a small stand and not for use. For looking at, dusting, and moving from the desk to the mantel and back. Its edge could not cut a sentence.", "0.90"),
]
assert sum(1 for k in KNIVES if k[2] == 79) == 1
assert all(k[2] == 79 or abs(k[2] - 79) >= 15 for k in KNIVES), "weights too close to 79"
