# (section, name, method, pairing). The cornbread pairing is the real clue; every other pairing is a red herring.
RECIPES = [
 # ---- Breads & Bakes
 ("Breads & Bakes", "Soda Bread", "Mix flour, a spoon of soda, and salt. Pour in buttermilk until a rough dough forms, shape into a round, cut a cross in the top, and bake hard and fast.", "Best eaten while playing the guitar, badly."),
 ("Breads & Bakes", "Oat Biscuits", "Rub butter into oats and flour, sweeten with brown sugar, bind with a little milk, and bake in small rounds until the edges darken.", "Best eaten while sweeping the window sills."),
 ("Breads & Bakes", "Yorkshire Pudding", "Beat eggs, flour, and milk into a thin batter and let it rest an hour. Pour into smoking-hot fat and do not open the oven door, whatever you hear.", "Best eaten after looking under the couch cushions."),
 ("Breads & Bakes", "Buttermilk Scones", "Cut cold butter into flour and a pinch of sugar, add buttermilk, and handle as little as possible. Bake tall and split while warm.", "Best enjoyed while playing the piano with one hand."),
 ("Breads & Bakes", "Rye Crackers", "Roll rye flour, water, salt, and caraway very thin, prick all over with a fork, and bake until they snap.", "Keep well in the sock drawer, wrapped in paper."),
 ("Breads & Bakes", "Cornbread", "Stir a cup of cornmeal into a cup of flour with a spoon of sugar, a pinch of salt, and a spoon of baking powder. Beat in an egg, a cup of milk, and a knob of melted butter. Bake in a hot, buttered tin until the top cracks and turns gold.", "Best eaten while playing a game of backgammon."),
 ("Breads & Bakes", "Banana Loaf", "Mash three tired bananas into butter and sugar, beat in an egg, fold in flour and soda, and bake slowly until a knife comes out clean.", "Best eaten while browsing an important gene-editing database."),
 ("Breads & Bakes", "Cheese Straws", "Roll pastry with grated hard cheese and a dust of mustard, cut into strips, twist, and bake until they crisp.", "Best served warm from the top rack of the dishwasher, which will not work, but is worth trying."),
 ("Breads & Bakes", "Potato Farls", "Mash yesterday's potatoes with flour and butter, press flat, cut into quarters, and fry dry in a hot pan.", "Best eaten under the stair railing."),
 ("Breads & Bakes", "Seed Cake", "Cream butter and sugar, beat in eggs, fold in flour and a spoon of caraway seeds, and bake in a loaf tin for an hour.", "Best eaten by the light of a bulb that needs changing."),
 ("Breads & Bakes", "Griddle Cakes", "Whisk flour, milk, an egg, and a pinch of soda into a batter and spoon onto a hot griddle. Flip when the bubbles burst.", "Best eaten while the laundry machine runs its last spin."),
 ("Breads & Bakes", "Gingerbread", "Melt butter with treacle and brown sugar, stir into flour, ginger, and soda, add an egg and milk, and bake until dark and springy.", "Best eaten on the top shelf of the linen closet."),
 # ---- Soups & Stews
 ("Soups & Stews", "Leek and Potato Soup", "Sweat sliced leeks in butter, add cubed potatoes and stock, simmer until soft, and mash roughly with a fork.", "Best eaten straight from the toaster oven, standing up."),
 ("Soups & Stews", "Split Pea Soup", "Soak peas overnight, then simmer with a ham bone, an onion, and a bay leaf until the peas collapse. Remove the bone and the bay leaf and keep the rest.", "Best eaten beside the spice drawer, with the drawer open."),
 ("Soups & Stews", "Tomato Soup", "Roast tomatoes and garlic until they blister, blend with stock and a splash of cream, and season generously.", "Best eaten beside the plant that needs repotting."),
 ("Soups & Stews", "Beef Stew", "Brown cubed beef in batches, add onions, carrots, a spoon of flour, and stock, and cook low and slow until the beef gives up.", "Best eaten while cleaning the paintbrushes."),
 ("Soups & Stews", "Chicken Broth", "Cover a chicken carcass with cold water, add an onion, celery, and peppercorns, and simmer gently for three hours. Strain and salt.", "Best taken between sets of push-ups."),
 ("Soups & Stews", "French Onion Soup", "Cook sliced onions in butter for an hour until they are brown and sweet, add stock and a splash of wine, and top each bowl with toast and melted cheese.", "Best eaten out of a cardboard box, sitting inside a larger cardboard box."),
 ("Soups & Stews", "Lentil Soup", "Soften onion, carrot, and cumin in oil, add red lentils and stock, and simmer until thick. Finish with lemon.", "Best eaten while losing at chess."),
 ("Soups & Stews", "Mushroom Soup", "Fry mushrooms hard in butter until they squeak, add thyme, stock, and cream, and blend until smooth.", "Best eaten while singing your favourite song at full volume."),
 ("Soups & Stews", "Fish Chowder", "Simmer potatoes and onion in milk, add chunks of white fish and a little bacon, and cook gently until the fish flakes.", "Best eaten while playing the songs everyone knows."),
 ("Soups & Stews", "Minestrone", "Cook beans, diced vegetables, and pasta in tomato stock until everything is tender, and stir in torn basil at the end.", "Best eaten over a game of chess, with the board turned the wrong way round."),
 ("Soups & Stews", "Pumpkin Soup", "Roast pumpkin with onion and sage, blend with stock, and add nutmeg and a swirl of cream.", "Best eaten during a game of checkers."),
 # ---- Dishes for the Evening
 ("Dishes for the Evening", "Shepherd's Pie", "Brown minced lamb with onion and carrot, add stock and a spoon of tomato paste, cover with mashed potato, and bake until the top browns.", "Best eaten while losing at Scrabble."),
 ("Dishes for the Evening", "Macaroni Cheese", "Make a white sauce with butter, flour, and milk, melt in a great deal of cheese, stir through cooked macaroni, and bake until bubbling.", "Best eaten while playing dominoes."),
 ("Dishes for the Evening", "Roast Chicken", "Rub a chicken with butter, salt, and thyme, put a lemon inside it, and roast until the legs wobble freely.", "Best eaten during a hand of cribbage."),
 ("Dishes for the Evening", "Toad in the Hole", "Brown sausages in a hot tin of fat, pour Yorkshire batter around them, and bake until the batter rises like a cliff.", "Best eaten over a game of cards, any game, any cards."),
 ("Dishes for the Evening", "Kedgeree", "Poach smoked haddock in milk, flake into buttered rice with curry powder, and fold through chopped boiled eggs and parsley.", "Best eaten while a tower of Jenga is being built."),
 ("Dishes for the Evening", "Fish Pie", "Poach white fish and prawns in milk, make the milk into a sauce, combine, top with mash, and bake.", "Best eaten while alphabetising the bookshelf."),
 ("Dishes for the Evening", "Sausage and Mash", "Fry sausages slowly until sticky, mash potatoes with too much butter, and pour onion gravy over the lot.", "Best eaten while finishing the crossword."),
 ("Dishes for the Evening", "Vegetable Curry", "Fry onion, ginger, and garlic with spices, add chopped vegetables, coconut milk, and chickpeas, and simmer until thick.", "Best eaten during a game of Uno."),
 ("Dishes for the Evening", "Baked Beans on Toast", "Warm beans with a spoon of brown sauce and a knob of butter, and pile onto thick buttered toast.", "Best eaten while a game of Monopoly is being abandoned."),
 ("Dishes for the Evening", "Bubble and Squeak", "Fry leftover mashed potato and cabbage in a hot pan until a crust forms, flip, and repeat.", "Best eaten in the bath."),
 ("Dishes for the Evening", "Welsh Rarebit", "Melt cheese with a spoon of mustard, a splash of ale, and an egg yolk, spread onto toast, and grill until it blisters.", "Best eaten on the fire escape."),
 ("Dishes for the Evening", "Pea Risotto", "Stir hot stock into rice and onion a ladle at a time, add peas and mint at the end, and finish with butter and cheese.", "Best eaten under the kitchen table."),
 ("Dishes for the Evening", "Lamb Chops", "Season chops, sear in a hot pan with rosemary, and rest them longer than seems reasonable.", "Best eaten with the freezer door open, standing up."),
 ("Dishes for the Evening", "Stuffed Peppers", "Fill halved peppers with cooked rice, tomato, herbs, and cheese, and bake until the edges char.", "Best eaten standing in the pantry."),
 ("Dishes for the Evening", "Omelette", "Beat three eggs with salt, pour into foaming butter, drag the edges toward the middle, and fold before it sets.", "Best eaten while watering the plants."),
 ("Dishes for the Evening", "Pork and Apple", "Sear pork chops, add sliced apples and a splash of cider, and simmer until the apples slump.", "Best eaten in bed, with a towel underneath."),
 ("Dishes for the Evening", "Mushroom Stroganoff", "Fry mushrooms and onion, add paprika, stock, and sour cream, and serve over rice or noodles.", "Best eaten with the curtains drawn."),
 # ---- Sides & Small Things
 ("Sides & Small Things", "Roast Potatoes", "Parboil potatoes, shake them roughly in the pan, and roast in hot fat until they rattle.", "Best eaten behind the bookshelf."),
 ("Sides & Small Things", "Buttered Cabbage", "Shred cabbage, cook briefly in a little water, drain, and toss with butter and black pepper.", "Best eaten from the bag of rice, which is not what the bag is for."),
 ("Sides & Small Things", "Pickled Onions", "Salt small onions overnight, rinse, and cover with spiced vinegar in a jar for a month.", "Best eaten nestled among the mixing bowls."),
 ("Sides & Small Things", "Deviled Eggs", "Halve boiled eggs, mash the yolks with mustard and mayonnaise, and pipe back into the whites with a dust of paprika.", "Best eaten after checking the mailbox."),
 ("Sides & Small Things", "Cheese on Toast", "Grate cheese, pile onto toast, and grill until it bubbles. Add Worcestershire sauce if you are that sort of person.", "Best eaten next to the toaster, watching it."),
 ("Sides & Small Things", "Garlic Bread", "Mash butter with garlic and parsley, spread into slashes cut in a loaf, wrap in foil, and bake.", "Best eaten atop a stepladder."),
 ("Sides & Small Things", "Potato Salad", "Boil waxy potatoes, cool, and dress with mayonnaise, chopped gherkins, and chives.", "Best eaten in a coat closet, among the coats."),
 ("Sides & Small Things", "Coleslaw", "Shred cabbage and carrot finely and dress with mayonnaise, a little vinegar, and a pinch of sugar.", "Best eaten on the balcony, whatever the weather."),
 ("Sides & Small Things", "Sautéed Greens", "Wilt greens in olive oil with garlic and chilli, and finish with lemon.", "Best eaten on the doormat."),
 ("Sides & Small Things", "Baked Tomatoes", "Halve tomatoes, top with breadcrumbs, garlic, and oil, and bake until soft.", "Best eaten under the cutting board, which is a strange place for it."),
 ("Sides & Small Things", "Corn on the Cob", "Boil corn for five minutes, roll in butter, and salt heavily.", "Best eaten while changing the bedsheets."),
 ("Sides & Small Things", "Cauliflower Cheese", "Boil cauliflower until just tender, cover with cheese sauce, and bake until the top browns.", "Best eaten from the dishwasher, on the top rack, unwashed."),
 ("Sides & Small Things", "Hummus", "Blend chickpeas with tahini, lemon, garlic, and oil until smooth, thinning with cold water.", "Best eaten after checking every coat pocket."),
 ("Sides & Small Things", "Welsh Cakes", "Rub butter into flour with sugar and currants, bind with an egg, roll, cut into rounds, and cook on a griddle.", "Best eaten over a game of Coup, trusting nobody."),
 # ---- Sweets
 ("Sweets", "Apple Crumble", "Stew sliced apples with sugar, top with a rubble of flour, butter, and oats, and bake until the juices bubble through.", "Best eaten under the bathroom sink."),
 ("Sweets", "Rice Pudding", "Bake rice slowly in sweetened milk with nutmeg for two hours, stirring in the skin as it forms.", "Best eaten with a scoop of protein powder, for reasons of science."),
 ("Sweets", "Bread and Butter Pudding", "Layer buttered bread and raisins in a dish, pour over sweet egg custard, rest, and bake until set.", "Best eaten under the rug."),
 ("Sweets", "Treacle Tart", "Warm golden syrup with breadcrumbs and lemon zest, pour into a pastry case, and bake until it just sets.", "Best eaten with the hallway light off."),
 ("Sweets", "Lemon Curd", "Whisk eggs, sugar, butter, and lemon over a low heat until thick, and pot while warm.", "Best eaten from the umbrella stand."),
 ("Sweets", "Shortbread", "Work butter, sugar, and flour into a dough, press into a tin, prick, and bake pale.", "Best eaten from the vegetable crisper."),
 ("Sweets", "Baked Apples", "Core apples, fill with brown sugar, butter, and raisins, and bake until they collapse.", "Best eaten while looking in the medicine cabinet."),
 ("Sweets", "Custard", "Warm milk, whisk into egg yolks and sugar, and return to the heat until it coats the back of a spoon.", "Best eaten out of the freezer, before it has thawed."),
 ("Sweets", "Jam Roly-Poly", "Roll suet pastry with jam, wrap in paper, and steam for two hours.", "Best eaten while ironing."),
 ("Sweets", "Sponge Cake", "Beat equal weights of butter, sugar, eggs, and flour, and bake in two tins. Sandwich with jam and cream.", "Best eaten while winding a clock."),
 ("Sweets", "Flapjacks", "Melt butter, sugar, and syrup, stir in oats, press into a tin, and bake until golden at the edges.", "Best eaten with the television on and the sound off."),
 ("Sweets", "Stewed Rhubarb", "Cook rhubarb with sugar and a splash of water until it falls apart, and cool.", "Best eaten with all the windows open."),
 ("Sweets", "Chocolate Pudding", "Melt chocolate with butter, fold into beaten eggs, sugar, and a spoon of flour, and bake in cups until the middle wobbles.", "Best eaten while tuning a guitar."),
 ("Sweets", "Pancakes", "Whisk flour, an egg, and milk into a thin batter and fry in butter. Lemon and sugar, no discussion.", "Best eaten while waiting for the kettle."),
 # ---- Drinks
 ("Drinks", "Hot Chocolate", "Melt dark chocolate into hot milk, whisk until frothy, and sweeten to taste.", "Best drunk beneath the desk."),
 ("Drinks", "Ginger Tea", "Simmer sliced ginger in water for ten minutes, strain, and add honey and lemon.", "Best drunk on the stairs, halfway up."),
 ("Drinks", "Lemon Barley Water", "Simmer pearl barley in water, strain, and add lemon juice, zest, and sugar. Chill.", "Best drunk in the shower, cold."),
 ("Drinks", "Mulled Cider", "Warm cider gently with cinnamon, cloves, and orange peel. Do not boil.", "Best drunk while checking the smoke alarm."),
 ("Drinks", "Iced Coffee", "Brew strong coffee, cool it entirely, and pour over ice with milk.", "Best drunk in the bicycle's shadow."),
 ("Drinks", "Egg Nog", "Beat egg yolks with sugar, add milk, cream, and nutmeg, and fold in whipped whites.", "Best drunk while looking through the peephole."),
]
